version: '3.8'
    
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/frontend:/usr/src/app/
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run start"
