version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/backend/:/usr/src/app
    ports:
      - 8000:8000
    command: ["uvicorn", "main:app","--host", "0.0.0.0", "--reload"]
