version: '3.8'

services:
  database:
    container_name: database
    build:
      context: ./database/
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/database/postgresql:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .database.env
